# -*- coding: utf-8 -*-
"""HigherOrLower.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C5QZOZHCeJt8l5jkA2V_MolMsn4pOxYx
"""

import random

def higher_or_lower():
    score = 0 #Keep Track of User Scre
    prev_number = random.randint(1, 100)
    incorrect_guesses = []
    while True:
        random_number = random.randint(1, 100)
        print("Number:", random_number)

        guess = input("Will the next number be higher (H) or lower (L) than the previous number? ").strip().lower()
        # Checking if the users input is valid for computer to read
        if guess != "h" and guess != "l":
            print("Invalid input. Please enter 'H' for higher or 'L' for lower.")
            continue

        # If statement that sees if the users guess was correct
        ## If score is correct then score gets updated by 1
        if (guess == "h" and random_number > prev_number) or (guess == "l" and random_number < prev_number):
            print("Correct!")
            score += 1
        # Incorrect guess showing what they gussed wrong on
        else:
            print("Incorrect You Guessed On: ",random_number)
            incorrect_guesses.append(random_number)
            break

        prev_number = random_number
        # Users final score
        print("Score:", score)

    print("Game Over. Your final score is:", score)

higher_or_lower()